version: '1.0'
services:
  postgres:
    image: postgres:13
    container_name: nestjs-typeorm
    restart: always
    ports:
      - 5444:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: nestjs-typeorm
